/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.c
**     Project     : Luchador Serial Fimware KL27
**     Processor   : MKL27Z256VLH4
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-12-03, 16:24, # CodeGen: 28
**     Abstract    :
**
**     Settings    :
**          Component name                                 : pin_mux
**          PinSettings IP Block                           : PinSettings
**          Processor                                      : MKL27Z256LH4
**          Pin settings                                   : 
**            Routing                                      : 
**              Peripheral Type ADC                        : 
**                Custom name                              : ADC0
**                ADC0                                     : 
**                  DM0 - Differential minus channel 0     : <Automatic>
**                  DM3 - Differential minus channel 3     : <Automatic>
**                  DP0 - Differential plus channel 0      : <Automatic>
**                  DP3 - Differential plus channel 3      : <Automatic>
**                  SE0 - Single-ended channel 0           : <Automatic>
**                  SE3 - Single-ended channel 3           : <Automatic>
**                  SE8 - Single-ended channel 8           : <Automatic>
**                  SE9 - Single-ended channel 9           : <Automatic>
**                  SE11 - Single-ended channel 11         : <Automatic>
**                  SE12 - Single-ended channel 12         : <Automatic>
**                  SE13 - Single-ended channel 13         : <Automatic>
**                  SE14 - Single-ended channel 14         : <Automatic>
**                  SE15 - Single-ended channel 15         : <Automatic>
**                  SE23 - Single-ended channel 23         : <Automatic>
**                  SE4a - Single-ended channel 4a         : <Automatic>
**                  SE7a - Single-ended channel 7a         : <Automatic>
**                  SE4b - Single-ended channel 4b         : <Automatic>
**                  SE5b - Single-ended channel 5b         : <Automatic>
**                  SE6b - Single-ended channel 6b         : <Automatic>
**                  SE7b - Single-ended channel 7b         : <Automatic>
**                  Trigger A input                        : <Automatic>
**                  Trigger B input                        : <Automatic>
**                  Voltage reference high                 : VDDA
**                  Voltage reference high                 : VREFH
**                  Voltage reference low                  : VREFL
**                  Voltage reference low                  : VSSA
**                Bool_ADC0                                : yes
**              Peripheral Type BP                         : 
**              Peripheral Type CMP                        : 
**                Custom name                              : CMP0
**                CMP0                                     : 
**                  IN0 - Input 0                          : <Automatic>
**                  IN1 - Input 1                          : <Automatic>
**                  IN2 - Input 2                          : <Automatic>
**                  IN3 - Input 3                          : <Automatic>
**                  IN4 - Input 4                          : <Automatic>
**                  IN5 - Input 5                          : <Automatic>
**                  OUT - Output                           : <Automatic>
**                Bool_CMP0                                : yes
**              Peripheral Type CoreDebug                  : 
**                Custom name                              : CoreDebug
**                CoreDebug                                : 
**                  CLK - Clock                            : <Automatic>
**                  DIO - Data input/output                : <Automatic>
**                Bool_CoreDebug                           : yes
**              Peripheral Type DAC                        : 
**                Custom name                              : DAC0
**                DAC0                                     : 
**                  OUT - Output pin                       : <Automatic>
**                  Trigger input                          : <Automatic>
**                Bool_DAC0                                : yes
**              Peripheral Type DMA                        : 
**                Custom name                              : DMA
**              Peripheral Type DMAMUX                     : 
**                Custom name                              : DMAMUX0
**              Peripheral Type DWT                        : 
**              Peripheral Type FLEXIO                     : 
**                Custom name                              : FLEXIO
**                FLEXIO                                   : 
**                  D0 - Data pin 0                        : <Automatic>
**                  D1 - Data pin 1                        : <Automatic>
**                  D2 - Data pin 2                        : <Automatic>
**                  D3 - Data pin 3                        : <Automatic>
**                  D4 - Data pin 4                        : <Automatic>
**                  D5 - Data pin 5                        : <Automatic>
**                  D6 - Data pin 6                        : <Automatic>
**                  D7 - Data pin 7                        : <Automatic>
**                Bool_FLEXIO                              : yes
**              Peripheral Type FTFA                       : 
**                Custom name                              : FTFA
**              Peripheral Type GPIO                       : 
**                Custom name                              : GPIOA
**                GPIOA                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : PTA4/I2C1_SDA/TPM0_CH1/NMI_b
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 12                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 13                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 18                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 19                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 20                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOA                               : yes
**                Custom name                              : GPIOB
**                GPIOB                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 16                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 17                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 18                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 19                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOB                               : yes
**                Custom name                              : GPIOC
**                GPIOC                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 8                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 9                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 10                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 11                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOC                               : yes
**                Custom name                              : GPIOD
**                GPIOD                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOD                               : yes
**                Custom name                              : GPIOE
**                GPIOE                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 20                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 21                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 22                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 23                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 24                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 25                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 29                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 30                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 31                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOE                               : yes
**              Peripheral Type I2C                        : 
**                Custom name                              : I2C0
**                I2C0                                     : 
**                  SCL - Serial clock                     : <Automatic>
**                  SDA - Serial data                      : <Automatic>
**                Bool_I2C0                                : yes
**                Custom name                              : I2C1
**                I2C1                                     : 
**                  SCL - Serial clock                     : <Automatic>
**                  SDA - Serial data                      : <Automatic>
**                Bool_I2C1                                : yes
**              Peripheral Type I2S                        : 
**                Custom name                              : I2S0
**                I2S0                                     : 
**                  MCLK - Master clock                    : <Automatic>
**                  Direction                              : <Automatic>
**                  RX_BCLK - RX bit clock                 : <Automatic>
**                  Direction                              : <Automatic>
**                  RX_FS - RX frame sync                  : <Automatic>
**                  Direction                              : <Automatic>
**                  RXD0 - Receive data 0                  : <Automatic>
**                  TX_BCLK - TX bit clock                 : <Automatic>
**                  Direction                              : <Automatic>
**                  TX_FS - TX frame sync                  : <Automatic>
**                  Direction                              : <Automatic>
**                  TXD0 - Transmit data 0                 : <Automatic>
**                Bool_I2S0                                : yes
**              Peripheral Type LCD                        : 
**              Peripheral Type LLWU                       : 
**                Custom name                              : LLWU
**                LLWU                                     : 
**                  P5 - Wake-up pin 5                     : <Automatic>
**                  P6 - Wake-up pin 6                     : <Automatic>
**                  P7 - Wake-up pin 7                     : <Automatic>
**                  P8 - Wake-up pin 8                     : <Automatic>
**                  P9 - Wake-up pin 9                     : <Automatic>
**                  P10 - Wake-up pin 10                   : <Automatic>
**                  P14 - Wake-up pin 14                   : <Automatic>
**                  P15 - Wake-up pin 15                   : <Automatic>
**                Bool_LLWU                                : yes
**              Peripheral Type LPTMR                      : 
**                Custom name                              : LPTMR0
**                LPTMR0                                   : 
**                  ALT0 - Pulse counter input 0           : <Automatic>
**                  ALT1 - Pulse counter input 1           : <Automatic>
**                  ALT2 - Pulse counter input 2           : <Automatic>
**                Bool_LPTMR0                              : yes
**              Peripheral Type LPUART                     : 
**                Custom name                              : LPUART0
**                LPUART0                                  : 
**                  RX - Receive data                      : PTA1/LPUART0_RX/TPM2_CH0
**                  TX - Transmit data                     : PTA2/LPUART0_TX/TPM2_CH1
**                Bool_LPUART0                             : yes
**                Custom name                              : LPUART1
**                LPUART1                                  : 
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_LPUART1                             : yes
**              Peripheral Type MCG                        : 
**                Custom name                              : MCG
**              Peripheral Type MCM                        : 
**                Custom name                              : MCM
**              Peripheral Type MTB                        : 
**              Peripheral Type MTBDWT                     : 
**              Peripheral Type NV                         : 
**                Custom name                              : FTFA_FlashConfig
**              Peripheral Type NVIC                       : 
**                Custom name                              : NVIC
**              Peripheral Type OSC                        : 
**                Custom name                              : OSC0
**                OSC0                                     : 
**                  External clock/Oscillator input        : <Automatic>
**                  Oscillator output                      : <Automatic>
**                Bool_OSC0                                : yes
**              Peripheral Type PIT                        : 
**                Custom name                              : PIT
**              Peripheral Type PMC                        : 
**                Custom name                              : PMC
**              Peripheral Type PORT                       : 
**                Custom name                              : PORTA
**                Custom name                              : PORTB
**                Custom name                              : PORTC
**                Custom name                              : PORTD
**                Custom name                              : PORTE
**              Peripheral Type RCM                        : 
**                Custom name                              : RCM
**                RCM                                      : 
**                  Reset input                            : <Automatic>
**                Bool_RCM                                 : yes
**              Peripheral Type RFSYS                      : 
**                Custom name                              : RFSYS
**              Peripheral Type ROM                        : 
**              Peripheral Type RTC                        : 
**                Custom name                              : RTC
**                RTC                                      : 
**                  CLKIN - Clock input                    : <Automatic>
**                  CLKOUT - Oscillator output             : <Automatic>
**                Bool_RTC                                 : yes
**              Peripheral Type SCB                        : 
**                Custom name                              : SystemControl
**                SystemControl                            : 
**                  NMI - Non-maskable interrupt           : <Automatic>
**                Bool_SystemControl                       : yes
**              Peripheral Type SIM                        : 
**                Custom name                              : SIM
**                SIM                                      : 
**                  Trace clock output                     : <Automatic>
**                  ERCLK32K clock output                  : <Automatic>
**                Bool_SIM                                 : yes
**              Peripheral Type SMC                        : 
**                Custom name                              : SMC
**              Peripheral Type SPI                        : 
**                Custom name                              : SPI0
**                SPI0                                     : 
**                  MISO - Master data in, slave data out  : <Automatic>
**                  Direction                              : <Automatic>
**                  MOSI - Master data out, slave data in  : <Automatic>
**                  Direction                              : <Automatic>
**                  SCK - Serial clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  SS - Slave select                      : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_SPI0                                : yes
**                Custom name                              : SPI1
**                SPI1                                     : 
**                  MISO - Master data in, slave data out  : <Automatic>
**                  Direction                              : <Automatic>
**                  MOSI - Master data out, slave data in  : <Automatic>
**                  Direction                              : <Automatic>
**                  SCK - Serial clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  SS - Slave select                      : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_SPI1                                : yes
**              Peripheral Type SUPPLY                     : 
**                SUPPLY                                   : 
**                  Chip power supply                      : VDD17
**                  Chip power supply                      : VDD94
**                  Chip power supply                      : VDD137
**                  Analog power supply                    : VDDA
**                  Chip ground                            : VSS18
**                  Chip ground                            : VSS95
**                  Chip ground                            : VSS136
**                  Analog ground                          : VSSA
**                Bool_SUPPLY                              : yes
**              Peripheral Type SysTick                    : 
**                Custom name                              : SysTick
**              Peripheral Type TPM                        : 
**                Custom name                              : TPM0
**                TPM0                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH2 - Channel 2                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH3 - Channel 3                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH4 - Channel 4                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH5 - Channel 5                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM0                                : yes
**                Custom name                              : TPM1
**                TPM1                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM1                                : yes
**                Custom name                              : TPM2
**                TPM2                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM2                                : yes
**              Peripheral Type UART                       : 
**                Custom name                              : UART2
**                UART2                                    : 
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_UART2                               : yes
**              Peripheral Type USB                        : 
**                Custom name                              : USB0
**                USB0                                     : 
**                  CLKIN - Alternate Clock                : <Automatic>
**                  DM - Data minus                        : USB0_DM
**                  DP - Data plus                         : USB0_DP
**                  SOF - Start of frame                   : <Automatic>
**                  Regulator output voltage               : VOUT33
**                  Unregulated power supply               : VREGIN
**                Bool_USB0                                : no
**              Peripheral Type VREF                       : 
**                Custom name                              : VREF
**              Non-peripheral pins                        : 
**            Electrical properties                        : 
**              Pin 1: PTE0/CLKOUT32K/SPI1_MISO/LPUART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA: 
**                Custom name, Signal name                 : PTE0/CLKOUT32K/SPI1_MISO/LPUART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 2: PTE1/SPI1_MOSI/LPUART1_RX/SPI1_MISO/I2C1_SCL: 
**                Custom name, Signal name                 : PTE1/SPI1_MOSI/LPUART1_RX/SPI1_MISO/I2C1_SCL
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 3: VDD17                               : 
**                Custom name, Signal name                 : VDD17
**              Pin 4: VSS18                               : 
**                Custom name, Signal name                 : VSS18
**              Pin 5: USB0_DP                             : 
**                Custom name, Signal name                 : USB0_DP
**              Pin 6: USB0_DM                             : 
**                Custom name, Signal name                 : USB0_DM
**              Pin 7: VOUT33                              : 
**                Custom name, Signal name                 : VOUT33
**              Pin 8: VREGIN                              : 
**                Custom name, Signal name                 : VREGIN
**              Pin 9: ADC0_DP0/ADC0_SE0/PTE20/TPM1_CH0/LPUART0_TX/FXIO0_D4: 
**                Custom name, Signal name                 : ADC0_DP0/ADC0_SE0/PTE20/TPM1_CH0/LPUART0_TX/FXIO0_D4
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 10: ADC0_DM0/ADC0_SE4a/PTE21/TPM1_CH1/LPUART0_RX/FXIO0_D5: 
**                Custom name, Signal name                 : ADC0_DM0/ADC0_SE4a/PTE21/TPM1_CH1/LPUART0_RX/FXIO0_D5
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 11: ADC0_DP3/ADC0_SE3/PTE22/TPM2_CH0/UART2_TX/FXIO0_D6: 
**                Custom name, Signal name                 : ADC0_DP3/ADC0_SE3/PTE22/TPM2_CH0/UART2_TX/FXIO0_D6
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 12: ADC0_DM3/ADC0_SE7a/PTE23/TPM2_CH1/UART2_RX/FXIO0_D7: 
**                Custom name, Signal name                 : ADC0_DM3/ADC0_SE7a/PTE23/TPM2_CH1/UART2_RX/FXIO0_D7
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 13: VDDA                               : 
**                Custom name, Signal name                 : VDDA
**              Pin 14: VREFH                              : 
**                Custom name, Signal name                 : VREFH
**              Pin 15: VREFL                              : 
**                Custom name, Signal name                 : VREFL
**              Pin 16: VSSA                               : 
**                Custom name, Signal name                 : VSSA
**              Pin 17: CMP0_IN5/ADC0_SE4b/PTE29/TPM0_CH2/TPM_CLKIN0: 
**                Custom name, Signal name                 : CMP0_IN5/ADC0_SE4b/PTE29/TPM0_CH2/TPM_CLKIN0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 18: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1/LPUART1_TX/LPTMR0_ALT1: 
**                Custom name, Signal name                 : DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1/LPUART1_TX/LPTMR0_ALT1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 19: PTE31/TPM0_CH4                     : 
**                Custom name, Signal name                 : PTE31/TPM0_CH4
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 20: PTE24/TPM0_CH0/I2C0_SCL            : 
**                Custom name, Signal name                 : PTE24/TPM0_CH0/I2C0_SCL
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 21: PTE25/TPM0_CH1/I2C0_SDA            : 
**                Custom name, Signal name                 : PTE25/TPM0_CH1/I2C0_SDA
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 22: PTA0/TPM0_CH5/SWD_CLK              : 
**                Custom name, Signal name                 : PTA0/TPM0_CH5/SWD_CLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 23: PTA1/LPUART0_RX/TPM2_CH0           : 
**                Custom name, Signal name                 : PTA1/LPUART0_RX/TPM2_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 24: PTA2/LPUART0_TX/TPM2_CH1           : 
**                Custom name, Signal name                 : PTA2/LPUART0_TX/TPM2_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 25: PTA3/I2C1_SCL/TPM0_CH0/SWD_DIO     : 
**                Custom name, Signal name                 : PTA3/I2C1_SCL/TPM0_CH0/SWD_DIO
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 26: PTA4/I2C1_SDA/TPM0_CH1/NMI_b       : 
**                Custom name, Signal name                 : PTA4/I2C1_SDA/TPM0_CH1/NMI_b
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 27: PTA5/USB_CLKIN/TPM0_CH2/I2S0_TX_BCLK: 
**                Custom name, Signal name                 : PTA5/USB_CLKIN/TPM0_CH2/I2S0_TX_BCLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 28: PTA12/TPM1_CH0/I2S0_TXD0           : 
**                Custom name, Signal name                 : PTA12/TPM1_CH0/I2S0_TXD0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 29: PTA13/TPM1_CH1/I2S0_TX_FS          : 
**                Custom name, Signal name                 : PTA13/TPM1_CH1/I2S0_TX_FS
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 30: VDD94                              : 
**                Custom name, Signal name                 : VDD94
**              Pin 31: VSS95                              : 
**                Custom name, Signal name                 : VSS95
**              Pin 32: EXTAL0/PTA18/LPUART1_RX/TPM_CLKIN0 : 
**                Custom name, Signal name                 : EXTAL0/PTA18/LPUART1_RX/TPM_CLKIN0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 33: XTAL0/PTA19/LPUART1_TX/TPM_CLKIN1/LPTMR0_ALT1: 
**                Custom name, Signal name                 : XTAL0/PTA19/LPUART1_TX/TPM_CLKIN1/LPTMR0_ALT1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 34: PTA20/RESET_b                      : 
**                Custom name, Signal name                 : PTA20/RESET_b
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 35: ADC0_SE8/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0: 
**                Custom name, Signal name                 : ADC0_SE8/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 36: ADC0_SE9/PTB1/I2C0_SDA/TPM1_CH1    : 
**                Custom name, Signal name                 : ADC0_SE9/PTB1/I2C0_SDA/TPM1_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 37: ADC0_SE12/PTB2/I2C0_SCL/TPM2_CH0   : 
**                Custom name, Signal name                 : ADC0_SE12/PTB2/I2C0_SCL/TPM2_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 38: ADC0_SE13/PTB3/I2C0_SDA/TPM2_CH1   : 
**                Custom name, Signal name                 : ADC0_SE13/PTB3/I2C0_SDA/TPM2_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 39: PTB16/SPI1_MOSI/LPUART0_RX/TPM_CLKIN0/SPI1_MISO: 
**                Custom name, Signal name                 : PTB16/SPI1_MOSI/LPUART0_RX/TPM_CLKIN0/SPI1_MISO
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 40: PTB17/SPI1_MISO/LPUART0_TX/TPM_CLKIN1/SPI1_MOSI: 
**                Custom name, Signal name                 : PTB17/SPI1_MISO/LPUART0_TX/TPM_CLKIN1/SPI1_MOSI
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 41: PTB18/TPM2_CH0/I2S0_TX_BCLK        : 
**                Custom name, Signal name                 : PTB18/TPM2_CH0/I2S0_TX_BCLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 42: PTB19/TPM2_CH1/I2S0_TX_FS          : 
**                Custom name, Signal name                 : PTB19/TPM2_CH1/I2S0_TX_FS
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 43: ADC0_SE14/PTC0/EXTRG_IN/USB_SOF_OUT/CMP0_OUT/I2S0_TXD0: 
**                Custom name, Signal name                 : ADC0_SE14/PTC0/EXTRG_IN/USB_SOF_OUT/CMP0_OUT/I2S0_TXD0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 44: ADC0_SE15/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0/I2S0_TXD0: 
**                Custom name, Signal name                 : ADC0_SE15/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0/I2S0_TXD0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 45: ADC0_SE11/PTC2/I2C1_SDA/TPM0_CH1/I2S0_TX_FS: 
**                Custom name, Signal name                 : ADC0_SE11/PTC2/I2C1_SDA/TPM0_CH1/I2S0_TX_FS
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 46: PTC3/LLWU_P7/SPI1_SCK/LPUART1_RX/TPM0_CH2/CLKOUT/I2S0_TX_BCLK: 
**                Custom name, Signal name                 : PTC3/LLWU_P7/SPI1_SCK/LPUART1_RX/TPM0_CH2/CLKOUT/I2S0_TX_BCLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 47: VSS136                             : 
**                Custom name, Signal name                 : VSS136
**              Pin 48: VDD137                             : 
**                Custom name, Signal name                 : VDD137
**              Pin 49: PTC4/LLWU_P8/SPI0_SS/LPUART1_TX/TPM0_CH3/I2S0_MCLK: 
**                Custom name, Signal name                 : PTC4/LLWU_P8/SPI0_SS/LPUART1_TX/TPM0_CH3/I2S0_MCLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 50: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/CMP0_OUT: 
**                Custom name, Signal name                 : PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/CMP0_OUT
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 51: CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK: 
**                Custom name, Signal name                 : CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 52: CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/I2S0_RX_FS/SPI0_MOSI: 
**                Custom name, Signal name                 : CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/I2S0_RX_FS/SPI0_MOSI
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 53: CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4/I2S0_MCLK: 
**                Custom name, Signal name                 : CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4/I2S0_MCLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 54: CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5/I2S0_RX_BCLK: 
**                Custom name, Signal name                 : CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5/I2S0_RX_BCLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 55: PTC10/I2C1_SCL/I2S0_RX_FS          : 
**                Custom name, Signal name                 : PTC10/I2C1_SCL/I2S0_RX_FS
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 56: PTC11/I2C1_SDA/I2S0_RXD0           : 
**                Custom name, Signal name                 : PTC11/I2C1_SDA/I2S0_RXD0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 57: PTD0/SPI0_SS/TPM0_CH0/FXIO0_D0     : 
**                Custom name, Signal name                 : PTD0/SPI0_SS/TPM0_CH0/FXIO0_D0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 58: ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1/FXIO0_D1: 
**                Custom name, Signal name                 : ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1/FXIO0_D1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 59: PTD2/SPI0_MOSI/UART2_RX/TPM0_CH2/SPI0_MISO/FXIO0_D2: 
**                Custom name, Signal name                 : PTD2/SPI0_MOSI/UART2_RX/TPM0_CH2/SPI0_MISO/FXIO0_D2
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 60: PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI/FXIO0_D3: 
**                Custom name, Signal name                 : PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI/FXIO0_D3
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 61: PTD4/LLWU_P14/SPI1_SS/UART2_RX/TPM0_CH4/FXIO0_D4: 
**                Custom name, Signal name                 : PTD4/LLWU_P14/SPI1_SS/UART2_RX/TPM0_CH4/FXIO0_D4
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 62: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5/FXIO0_D5: 
**                Custom name, Signal name                 : ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5/FXIO0_D5
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 63: ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/LPUART0_RX/SPI1_MISO/FXIO0_D6: 
**                Custom name, Signal name                 : ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/LPUART0_RX/SPI1_MISO/FXIO0_D6
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 64: PTD7/SPI1_MISO/LPUART0_TX/SPI1_MOSI/FXIO0_D7: 
**                Custom name, Signal name                 : PTD7/SPI1_MISO/LPUART0_TX/SPI1_MOSI/FXIO0_D7
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**          Settings                                       : 
**            Clock gates initialization mode              : SIM HAL (fsl_sim_hal component)
**            Inherited HAL components                     : 
**              fsl_port_hal                               : fsl_port_hal
**              fsl_sim_hal                                : fsl_sim_hal
**              HAL fsl_mcglite_hal                        : fsl_mcglite_hal
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.c
** @version 1.4
** @brief
**
*/         
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/         

#if !defined(__BOARD_H__)
#define __BOARD_H__

#include <stdint.h>
#include "pin_mux.h"


#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

void hardware_init(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus */

#endif /* __BOARD_H__ */

