/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : clockMan1.h
**     Project     : Luchador Serial Fimware KL27
**     Processor   : MKL27Z256VLH4
**     Component   : fsl_clock_manager
**     Version     : Component 1.3.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-11-26, 10:10, # CodeGen: 0
**     Contents    :
**         CLOCK_SYS_SetOutDiv1                  - static inline void CLOCK_SYS_SetOutDiv1(uint8_t outdiv1);
**         CLOCK_SYS_GetOutDiv1                  - static inline uint8_t CLOCK_SYS_GetOutDiv1(void);
**         CLOCK_SYS_SetOutDiv4                  - static inline void CLOCK_SYS_SetOutDiv4(uint8_t outdiv4);
**         CLOCK_SYS_GetOutDiv4                  - static inline uint8_t CLOCK_SYS_GetOutDiv4(void);
**         CLOCK_SYS_SetOutDiv                   - static inline void CLOCK_SYS_SetOutDiv(uint8_t outdiv1,uint8_t...
**         CLOCK_SYS_GetOutDiv                   - static inline void CLOCK_SYS_GetOutDiv(uint8_t * outdiv1,uint8_t *...
**         CLOCK_SYS_GetInternalRefClockFreq     - static inline uint32_t CLOCK_SYS_GetInternalRefClockFreq(void);
**         CLOCK_SYS_GetExternalRefClock32kFreq  - uint32_t CLOCK_SYS_GetExternalRefClock32kFreq(void);
**         CLOCK_SYS_SetExternalRefClock32kSrc   - static inline void CLOCK_SYS_SetExternalRefClock32kSrc(clock_er32k_src_t src);
**         CLOCK_SYS_GetExternalRefClock32kSrc   - static inline clock_er32k_src_t CLOCK_SYS_GetExternalRefClock32kSrc(void);
**         CLOCK_SYS_GetOsc0ExternalRefClockFreq - uint32_t CLOCK_SYS_GetOsc0ExternalRefClockFreq(void);
**         CLOCK_SYS_GetRtcOutFreq               - uint32_t CLOCK_SYS_GetRtcOutFreq(void);
**         CLOCK_SYS_GetRtcOutSrc                - static inline clock_rtcout_src_t CLOCK_SYS_GetRtcOutSrc(void);
**         CLOCK_SYS_SetRtcOutSrc                - static inline void CLOCK_SYS_SetRtcOutSrc(clock_rtcout_src_t src);
**         CLOCK_SYS_GetRtcFreq                  - static inline uint32_t CLOCK_SYS_GetRtcFreq(uint32_t instance);
**         CLOCK_SYS_GetCopFreq                  - uint32_t CLOCK_SYS_GetCopFreq(void);
**         CLOCK_SYS_SetCopSrc                   - static inline void CLOCK_SYS_SetCopSrc(clock_cop_src_t copSrc);
**         CLOCK_SYS_GetCopSrc                   - static inline clock_cop_src_t CLOCK_SYS_GetCopSrc(void);
**         CLOCK_SYS_GetTpmFreq                  - uint32_t CLOCK_SYS_GetTpmFreq(uint32_t instance);
**         CLOCK_SYS_SetTpmSrc                   - static inline void CLOCK_SYS_SetTpmSrc(uint32_t instance,clock_tpm_src_t...
**         CLOCK_SYS_GetTpmSrc                   - static inline clock_tpm_src_t CLOCK_SYS_GetTpmSrc(uint32_t instance);
**         CLOCK_SYS_GetTpmExternalFreq          - uint32_t CLOCK_SYS_GetTpmExternalFreq(uint32_t instance);
**         CLOCK_SYS_SetTpmExternalSrc           - static inline void CLOCK_SYS_SetTpmExternalSrc(uint32_t...
**         CLOCK_SYS_GetTpmExternalSrc           - static inline sim_tpm_clk_sel_t CLOCK_SYS_GetTpmExternalSrc(uint32_t instance);
**         CLOCK_SYS_GetUsbfsFreq                - uint32_t CLOCK_SYS_GetUsbfsFreq(uint32_t instance);
**         CLOCK_SYS_SetUsbfsSrc                 - static inline void CLOCK_SYS_SetUsbfsSrc(uint32_t instance,clock_usbfs_src_t...
**         CLOCK_SYS_GetUsbfsSrc                 - static inline clock_usbfs_src_t CLOCK_SYS_GetUsbfsSrc(uint32_t instance);
**         CLOCK_SYS_GetLpuartSrc                - static inline clock_lpuart_src_t CLOCK_SYS_GetLpuartSrc(uint32_t instance);
**         CLOCK_SYS_SetLpuartSrc                - static inline void CLOCK_SYS_SetLpuartSrc(uint32_t...
**         CLOCK_SYS_GetLpuartFreq               - uint32_t CLOCK_SYS_GetLpuartFreq(uint32_t instance);
**         CLOCK_SYS_GetFlexioFreq               - uint32_t CLOCK_SYS_GetFlexioFreq(uint32_t instance);
**         CLOCK_SYS_SetFlexioSrc                - static inline void CLOCK_SYS_SetFlexioSrc(uint32_t...
**         CLOCK_SYS_GetFlexioSrc                - static inline clock_flexio_src_t CLOCK_SYS_GetFlexioSrc(uint32_t instance);
**         CLOCK_SYS_GetSaiFreq                  - uint32_t CLOCK_SYS_GetSaiFreq(uint32_t instance,clock_sai_src_t saiSrc);
**         CLOCK_SYS_GetFtfFreq                  - static inline uint32_t CLOCK_SYS_GetFtfFreq(uint32_t instance);
**         CLOCK_SYS_GetCrcFreq                  - static inline uint32_t CLOCK_SYS_GetCrcFreq(uint32_t instance);
**         CLOCK_SYS_GetCmpFreq                  - static inline uint32_t CLOCK_SYS_GetCmpFreq(uint32_t instance);
**         CLOCK_SYS_GetVrefFreq                 - static inline uint32_t CLOCK_SYS_GetVrefFreq(uint32_t instance);
**         CLOCK_SYS_GetSpiFreq                  - uint32_t CLOCK_SYS_GetSpiFreq(uint32_t instance);
**         CLOCK_SYS_GetI2cFreq                  - static inline uint32_t CLOCK_SYS_GetI2cFreq(uint32_t instance);
**         CLOCK_SYS_GetPitFreq                  - static inline uint32_t CLOCK_SYS_GetPitFreq(uint32_t instance);
**         CLOCK_SYS_GetAdcAltFreq               - static inline uint32_t CLOCK_SYS_GetAdcAltFreq(uint32_t instance);
**         CLOCK_SYS_GetUartFreq                 - static inline uint32_t CLOCK_SYS_GetUartFreq(uint32_t instance);
**         CLOCK_SYS_EnablePortClock             - void CLOCK_SYS_EnablePortClock(uint32_t instance);
**         CLOCK_SYS_DisablePortClock            - void CLOCK_SYS_DisablePortClock(uint32_t instance);
**         CLOCK_SYS_GetPortGateCmd              - bool CLOCK_SYS_GetPortGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableFtfClock              - static inline void CLOCK_SYS_EnableFtfClock(uint32_t instance);
**         CLOCK_SYS_DisableFtfClock             - static inline void CLOCK_SYS_DisableFtfClock(uint32_t instance);
**         CLOCK_SYS_GetFtfGateCmd               - static inline bool CLOCK_SYS_GetFtfGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableAdcClock              - void CLOCK_SYS_EnableAdcClock(uint32_t instance);
**         CLOCK_SYS_DisableAdcClock             - void CLOCK_SYS_DisableAdcClock(uint32_t instance);
**         CLOCK_SYS_GetAdcGateCmd               - bool CLOCK_SYS_GetAdcGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableCmpClock              - static inline void CLOCK_SYS_EnableCmpClock(uint32_t instance);
**         CLOCK_SYS_DisableCmpClock             - static inline void CLOCK_SYS_DisableCmpClock(uint32_t instance);
**         CLOCK_SYS_GetCmpGateCmd               - static inline bool CLOCK_SYS_GetCmpGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableVrefClock             - static inline void CLOCK_SYS_EnableVrefClock(uint32_t instance);
**         CLOCK_SYS_DisableVrefClock            - static inline void CLOCK_SYS_DisableVrefClock(uint32_t instance);
**         CLOCK_SYS_GetVrefGateCmd              - static inline bool CLOCK_SYS_GetVrefGateCmd(uint32_t instance);
**         CLOCK_SYS_GetLptmrFreq                - uint32_t CLOCK_SYS_GetLptmrFreq(uint32_t instance,clock_lptmr_src_t lptmrSrc);
**         CLOCK_SYS_EnableLptmrClock            - static inline void CLOCK_SYS_EnableLptmrClock(uint32_t instance);
**         CLOCK_SYS_DisableLptmrClock           - static inline void CLOCK_SYS_DisableLptmrClock(uint32_t instance);
**         CLOCK_SYS_GetLptmrGateCmd             - static inline bool CLOCK_SYS_GetLptmrGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableRtcClock              - static inline void CLOCK_SYS_EnableRtcClock(uint32_t instance);
**         CLOCK_SYS_DisableRtcClock             - static inline void CLOCK_SYS_DisableRtcClock(uint32_t instance);
**         CLOCK_SYS_GetRtcGateCmd               - static inline bool CLOCK_SYS_GetRtcGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableDacClock              - static inline void CLOCK_SYS_EnableDacClock(uint32_t instance);
**         CLOCK_SYS_DisableDacClock             - static inline void CLOCK_SYS_DisableDacClock(uint32_t instance);
**         CLOCK_SYS_GetDacGateCmd               - static inline bool CLOCK_SYS_GetDacGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableSpiClock              - void CLOCK_SYS_EnableSpiClock(uint32_t instance);
**         CLOCK_SYS_DisableSpiClock             - void CLOCK_SYS_DisableSpiClock(uint32_t instance);
**         CLOCK_SYS_GetSpiGateCmd               - bool CLOCK_SYS_GetSpiGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableI2cClock              - void CLOCK_SYS_EnableI2cClock(uint32_t instance);
**         CLOCK_SYS_DisableI2cClock             - void CLOCK_SYS_DisableI2cClock(uint32_t instance);
**         CLOCK_SYS_GetI2cGateCmd               - bool CLOCK_SYS_GetI2cGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableLpuartClock           - void CLOCK_SYS_EnableLpuartClock(uint32_t instance);
**         CLOCK_SYS_DisableLpuartClock          - void CLOCK_SYS_DisableLpuartClock(uint32_t instance);
**         CLOCK_SYS_GetLpuartGateCmd            - bool CLOCK_SYS_GetLpuartGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableUartClock             - static inline void CLOCK_SYS_EnableUartClock(uint32_t instance);
**         CLOCK_SYS_DisableUartClock            - static inline void CLOCK_SYS_DisableUartClock(uint32_t instance);
**         CLOCK_SYS_GetUartGateCmd              - static inline bool CLOCK_SYS_GetUartGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableUsbfsClock            - static inline void CLOCK_SYS_EnableUsbfsClock(uint32_t instance);
**         CLOCK_SYS_DisableUsbfsClock           - static inline void CLOCK_SYS_DisableUsbfsClock(uint32_t instance);
**         CLOCK_SYS_GetUsbfsGateCmd             - static inline bool CLOCK_SYS_GetUsbfsGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableFlexioClock           - static inline void CLOCK_SYS_EnableFlexioClock(uint32_t instance);
**         CLOCK_SYS_DisableFlexioClock          - static inline void CLOCK_SYS_DisableFlexioClock(uint32_t instance);
**         CLOCK_SYS_GetFlexioGateCmd            - static inline bool CLOCK_SYS_GetFlexioGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableDmaClock              - static inline void CLOCK_SYS_EnableDmaClock(uint32_t instance);
**         CLOCK_SYS_DisableDmaClock             - static inline void CLOCK_SYS_DisableDmaClock(uint32_t instance);
**         CLOCK_SYS_GetDmaGateCmd               - static inline bool CLOCK_SYS_GetDmaGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableDmamuxClock           - static inline void CLOCK_SYS_EnableDmamuxClock(uint32_t instance);
**         CLOCK_SYS_DisableDmamuxClock          - static inline void CLOCK_SYS_DisableDmamuxClock(uint32_t instance);
**         CLOCK_SYS_GetDmamuxGateCmd            - static inline bool CLOCK_SYS_GetDmamuxGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableSaiClock              - static inline void CLOCK_SYS_EnableSaiClock(uint32_t instance);
**         CLOCK_SYS_DisableSaiClock             - static inline void CLOCK_SYS_DisableSaiClock(uint32_t instance);
**         CLOCK_SYS_GetSaiGateCmd               - static inline bool CLOCK_SYS_GetSaiGateCmd(uint32_t instance);
**         CLOCK_SYS_EnablePitClock              - static inline void CLOCK_SYS_EnablePitClock(uint32_t instance);
**         CLOCK_SYS_DisablePitClock             - static inline void CLOCK_SYS_DisablePitClock(uint32_t instance);
**         CLOCK_SYS_GetPitGateCmd               - static inline bool CLOCK_SYS_GetPitGateCmd(uint32_t instance);
**         CLOCK_SYS_EnableTpmClock              - void CLOCK_SYS_EnableTpmClock(uint32_t instance);
**         CLOCK_SYS_DisableTpmClock             - void CLOCK_SYS_DisableTpmClock(uint32_t instance);
**         CLOCK_SYS_GetTpmGateCmd               - bool CLOCK_SYS_GetTpmGateCmd(uint32_t instance);
**         CLOCK_SYS_SetUsbExternalFreq          - static inline void CLOCK_SYS_SetUsbExternalFreq(uint32_t srcInstance,uint32_t...
**         CLOCK_SYS_SetTpmExternalFreq          - static inline void CLOCK_SYS_SetTpmExternalFreq(uint32_t srcInstance,uint32_t...
**         CLOCK_SYS_Init                        - clock_manager_error_code_t CLOCK_SYS_Init(clock_manager_user_config_t const...
**         CLOCK_SYS_UpdateConfiguration         - clock_manager_error_code_t CLOCK_SYS_UpdateConfiguration(uint8_t...
**         CLOCK_SYS_SetConfiguration            - clock_manager_error_code_t CLOCK_SYS_Se...
**         CLOCK_SYS_GetCurrentConfiguration     - uint8_t CLOCK_SYS_GetCurrentConfiguration(void);
**         CLOCK_SYS_GetErrorCallback            - clock_manager_callback_user_config_t* CLOCK_SYS_GetErrorCallback(void);
**         CLOCK_SYS_SetMcgliteMode              - mcglite_mode_error_t CLOCK_SYS_SetMcgliteMode(mcglite_config_t const *...
**         CLOCK_SYS_SetSimConfigration          - void CLOCK_SYS_SetSimConfigration(sim_config_t const * simConfig);
**         CLOCK_SYS_OscInit                     - clock_manager_error_code_t CLOCK_SYS_OscInit(uint32_t...
**         CLOCK_SYS_OscDeinit                   - void CLOCK_SYS_OscDeinit(uint32_t instance);
**         CLOCK_SYS_SetOscerConfigration        - void CLOCK_SYS_SetOscerConfigration(uint32_t instance,oscer_config_t const *...
**         CLOCK_SYS_RtcOscInit                  - clock_manager_error_code_t CLOCK_SYS_RtcOscInit(uint32_t...
**         CLOCK_SYS_RtcOscDeinit                - void CLOCK_SYS_RtcOscDeinit(uint32_t instance);
**         CLOCK_SYS_GetFreq                     - clock_manager_error_code_t CLOCK_SYS_GetFreq(clock_names_t clockName,uint32_t...
**         CLOCK_SYS_GetCoreClockFreq            - uint32_t CLOCK_SYS_GetCoreClockFreq(void);
**         CLOCK_SYS_GetSystemClockFreq          - uint32_t CLOCK_SYS_GetSystemClockFreq(void);
**         CLOCK_SYS_GetBusClockFreq             - uint32_t CLOCK_SYS_GetBusClockFreq(void);
**         CLOCK_SYS_GetFlashClockFreq           - uint32_t CLOCK_SYS_GetFlashClockFreq(void);
**         CLOCK_SYS_GetLpoClockFreq             - static inline uint32_t CLOCK_SYS_GetLpoClockFreq(void);
**         CLOCK_SYS_SetSystickSrc               - static inline void CLOCK_SYS_SetSystickSrc(clock_systick_src_t src);
**         CLOCK_SYS_GetSystickFreq              - inline uint32_t CLOCK_SYS_GetSystickFreq(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file clockMan1.h
** @version 01.00
*/         
/*!
**  @addtogroup clockMan1_module clockMan1 module documentation
**  @{
*/         
#ifndef __clockMan1_H
#define __clockMan1_H
/* MODULE clockMan1. */
        
/* Include inherited beans */
#include "osa1.h"
#include "Cpu.h"
        


/*! @brief Count of user Callbacks */
#define FSL_CLOCK_MANAGER_CALLBACK_CNT 0U
            
/*! @brief Array of User callbacks */
extern clock_manager_callback_user_config_t *g_clockManCallbacksArr[];
#endif /* ifndef __clockMan1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
        
