/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.c
**     Project     : Luchador Serial Fimware KL27
**     Processor   : MKL27Z256VLH4
**     Component   : MKL27Z256LH4
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Datasheet   : KL27P64M48SF6RM, Rev.3, Aug 2014
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-12-13, 15:03, # CodeGen: 45
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         SystemInit            - void SystemInit(void);
**         SystemCoreClockUpdate - void SystemCoreClockUpdate(void);
**
**     (c) Freescale Semiconductor, Inc.
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

/* {Default RTOS Adapter} No RTOS includes */
#include "Cpu.h"
#include "Events.h"


#ifdef __cplusplus
extern "C" {
#endif

/*
** ===================================================================
**     Method      :  Common_Init (component MKL27Z256LH4)
**     Description :
**         Initialization of registers for that there is no 
**         initialization component.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMMON_INIT
void Common_Init(void)
{
}

#endif /* CPU_COMMON_INIT */
/*
** ===================================================================
**     Method      :  Components_Init (component MKL27Z256LH4)
**     Description :
**         Initialization of components (with exception for Peripheral
**         Initialization Components which are initialized in 
**         Peripherals_Init() method).
**         For example, if automatic initialization feature 
**         is enabled in LDD component then its Init method call 
**         is executed in Components_Init() method.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMPONENTS_INIT
void Components_Init(void)
{

  /*! spiCom1 Auto initialization start */
  SPI_DRV_MasterInit(spiCom1_IDX, &spiCom1_MasterState);
  SPI_DRV_MasterConfigureBus(spiCom1_IDX, &spiCom1_MasterConfig0, &spiCom1_calculatedBaudRate);
  /*! spiCom1 Auto initialization end */
  
  /*! RgbLed Auto initialization start */
  GPIO_DRV_Init(NULL,RgbLed_OutConfig0);
  /*! RgbLed Auto initialization end */
  
  /*! StatusLed Auto initialization start */
  GPIO_DRV_Init(NULL,StatusLed_OutConfig0);
  /*! StatusLed Auto initialization end */
  
  /*! GpioEeg Auto initialization start */
  NVIC_SetPriority(PORTA_IRQn, 1U);
  OSA_InstallIntHandler(PORTA_IRQn,  GpioEeg_PORTA_IRQHandler);
  GPIO_DRV_Init(GpioEeg_InpConfig0,GpioEeg_OutConfig0);
  /*! GpioEeg Auto initialization end */
  
  /*! pitTimer1 Auto initialization start */
  OSA_InstallIntHandler(PIT_IRQn,  pitTimer1_IRQHandler);
  PIT_DRV_Init(pitTimer1_IDX,true);
  PIT_DRV_InitChannel(pitTimer1_IDX,pitTimer1_CHANNEL,&pitTimer1_InitConfig0);
  PIT_DRV_StartTimer(pitTimer1_IDX,pitTimer1_CHANNEL);
  /*! pitTimer1 Auto initialization end */
  /*! HardwareVersion Auto initialization start */
  GPIO_DRV_Init(HardwareVersion_InpConfig0,NULL);
  /*! HardwareVersion Auto initialization end */
  
  /*! AuxGpio Auto initialization start */
  GPIO_DRV_Init(NULL,AuxGpio_OutConfig0);
  /*! AuxGpio Auto initialization end */
  
  /*! dmaController1 Auto initialization start */
  DMA_DRV_Init(&dmaController1_State);
  /*! dmaController1 Auto initialization end */
  
  /*! DataUart with DMA Auto initialization start */
  LPUART_DRV_DmaInit(DataUart_IDX,&DataUart_State,&DataUart_InitConfig0);
  /*! DataUart with DMA Auto initialization end */    
  /*! MarkUart Auto initialization start */
  LPUART_DRV_Init(MarkUart_IDX,&MarkUart_State,&MarkUart_InitConfig0);
  /*! MarkUart Auto initialization end */
  /*! Adc Auto initialization start */
  ADC16_DRV_Init(Adc_IDX, &Adc_InitConfig0);
  ADC16_DRV_ConfigConvChn(Adc_IDX, 0U, &Adc_2_5VP);
  /*! Adc Auto initialization end */

}
#endif /* CPU_COMPONENTS_INIT */


#ifdef __cplusplus
}
#endif

/* END Cpu. */

