/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : dmaController1.h
**     Project     : Luchador Serial Fimware KL27
**     Processor   : MKL27Z256VLH4
**     Component   : fsl_dma
**     Version     : Component 1.3.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-12-08, 16:36, # CodeGen: 38
**     Contents    :
**         DMA_DRV_Init                  - dma_status_t DMA_DRV_Init(dma_state_t * state);
**         DMA_DRV_Deinit                - dma_status_t DMA_DRV_Deinit(void);
**         DMA_DRV_SetDestTransferSize   - dma_status_t DMA_DRV_SetDestTransferSize(dma_channel_t * chn,uint32_t...
**         DMA_DRV_SetSourceTransferSize - dma_status_t DMA_DRV_SetSourceTransferSize(dma_channel_t * chn,uint32_t...
**         DMA_DRV_RegisterCallback      - dma_status_t DMA_DRV_RegisterCallback(dma_channel_t * chn,dma_callback_t...
**         DMA_DRV_GetUnfinishedBytes    - uint32_t DMA_DRV_GetUnfinishedBytes(dma_channel_t * chn);
**         DMA_DRV_ClaimChannel          - dma_status_t DMA_DRV_ClaimChannel(uint32_t channel,dma_request_source_t...
**         DMA_DRV_RequestChannel        - uint32_t DMA_DRV_RequestChannel(uint32_t channel,dma_request_source_t...
**         DMA_DRV_FreeChannel           - dma_status_t DMA_DRV_FreeChannel(dma_channel_t * chn);
**         DMA_DRV_StartChannel          - dma_status_t DMA_DRV_StartChannel(dma_channel_t * chn);
**         DMA_DRV_StopChannel           - dma_status_t DMA_DRV_StopChannel(dma_channel_t * chn);
**         DMA_DRV_ConfigTransfer        - dma_status_t DMA_DRV_ConfigTransfer(dma_channel_t * chn,dma_transfer_type_t...
**         DMA_DRV_ConfigChanLink        - dma_status_t DMA_DRV_ConfigChanLink(dma_channel_t *...
**         DMA_DRV_IRQhandler            - void DMA_DRV_IRQhandler(uint32_t channel);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file dmaController1.h
** @version 01.00
*/         
/*!
**  @addtogroup dmaController1_module dmaController1 module documentation
**  @{
*/         
#ifndef __dmaController1_H
#define __dmaController1_H
/* MODULE dmaController1. */

/* Include inherited beans */
#include "clockMan1.h"
#include "osa1.h"
#include "Cpu.h"

/*! @brief Device instance number */
#define dmaController1_IDX DMA_IDX
/*! @brief Device instance number for backward compatibility */
#define FSL_DMACONTROLLER1 dmaController1_IDX

/*! @brief Driver state structure which holds driver runtime data */
extern dma_state_t dmaController1_State;

/*! @brief Dma channel 0 ISR */
void DMA0_IRQHandler(void);
/*! @brief Dma channel 1 ISR */
void DMA1_IRQHandler(void);
/*! @brief Dma channel 2 ISR */
void DMA2_IRQHandler(void);
/*! @brief Dma channel 3 ISR */
void DMA3_IRQHandler(void);

#endif
/* ifndef __dmaController1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
