/**
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 prepare.js

 Generates lib/version.js
 Set environment variable DEV=1 to append git hash to version string
 */


'use strict';

const util = require('util');
const exec = util.promisify(require('child_process').exec);
const fs = require('fs');
const path = require('path');

var pjson = require('../package.json');
var VERSION_DIR = 'lib'
var VERSION_FILE = 'version.js';

(async function(dir, file, pversion) {

  var githash = '';
  if (process.env.DEV) {
    const o = await exec('git log -1 --pretty=format:%h');
    githash = '-' + o.stdout;
  }

  if (!fs.existsSync(VERSION_DIR)) {
    fs.mkdirSync(VERSION_DIR);
  }

  let target = path.join(VERSION_DIR, VERSION_FILE);
  if (fs.existsSync(target)) {
    fs.unlinkSync(target);
  }

  var str = '// Auto-generated by npm run prepare\nmodule.exports = \'' +
      pversion + githash + '\';';
  fs.writeFile(target, str, 'utf8', function(err) {
    if (err) {
      throw err;
    }
  });

})(VERSION_DIR, VERSION_FILE, pjson.version);
